### ISSUE TITLE
CNN training in BOINC

### ISSUE THREAD

**Issue by bhack** [travisdesell/tao#2]
Do you have a plan to train CNN network in BOINC?
Are you interested in this https://github.com/BVLC/caffe/pull/1148?

**Comment by travisdesell** [comment]
Hi!

That is the eventual plan yes.  It looks like your software does some CNN work as well? Do you do any pretraining with RBMs?

--Travis


---------------------------------------------------------------------------
Travis Desell,  Assistant Professor
University of North Dakota - Dept. of Computer Science 
Streibel Hall Room 220
3950 Campus Road Stop 9015
Grand Forks, North Dakota 58202-9015
cell: 518-867-1054, office: 701-777-3477

Citizen Science Grid ( http://volunteer.cs.und.edu/csg )
MilkyWay@Home ( http://milkyway.cs.rpi.edu/ )
Homepage ( http://people.cs.und.edu/~tdesell/ )
----------------------------------------------------------------------------

**Comment by bhack** [comment]
You can find info on available layers types [here](http://caffe.berkeleyvision.org/tutorial/).
There was some recent initiative by @cbalint13 to start working on RBMs at https://github.com/BVLC/caffe/issues/1207
